# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class InformationStub(object):
  """The information service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InsertTrajectory = channel.unary_unary(
        '/message.Information/InsertTrajectory',
        request_serializer=message__pb2.Trajectory.SerializeToString,
        response_deserializer=message__pb2.InsertTrajectoryReply.FromString,
        )
    self.GetParams = channel.unary_unary(
        '/message.Information/GetParams',
        request_serializer=message__pb2.GetParamsRequest.SerializeToString,
        response_deserializer=message__pb2.ModelParams.FromString,
        )
    self.Quit = channel.unary_unary(
        '/message.Information/Quit',
        request_serializer=message__pb2.QuitRequest.SerializeToString,
        response_deserializer=message__pb2.QuitReply.FromString,
        )


class InformationServicer(object):
  """The information service definition.
  """

  def InsertTrajectory(self, request, context):
    """Sends an ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetParams(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Quit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InformationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InsertTrajectory': grpc.unary_unary_rpc_method_handler(
          servicer.InsertTrajectory,
          request_deserializer=message__pb2.Trajectory.FromString,
          response_serializer=message__pb2.InsertTrajectoryReply.SerializeToString,
      ),
      'GetParams': grpc.unary_unary_rpc_method_handler(
          servicer.GetParams,
          request_deserializer=message__pb2.GetParamsRequest.FromString,
          response_serializer=message__pb2.ModelParams.SerializeToString,
      ),
      'Quit': grpc.unary_unary_rpc_method_handler(
          servicer.Quit,
          request_deserializer=message__pb2.QuitRequest.FromString,
          response_serializer=message__pb2.QuitReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'message.Information', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
