# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='message',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x12\x07message\"(\n\x15InsertTrajectoryReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x12\n\x10GetParamsRequest\"\r\n\x0bQuitRequest\"\x0b\n\tQuitReply\"5\n\x0eGetParamsReply\x12\x13\n\x0b\x66rame_count\x18\x01 \x01(\x05\x12\x0e\n\x06params\x18\x02 \x01(\t\"\x83\x01\n\x08\x41gentOut\x12$\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x14.message.TensorInt32\x12+\n\rpolicy_logits\x18\x02 \x01(\x0b\x32\x14.message.TensorFloat\x12$\n\x06values\x18\x03 \x01(\x0b\x32\x14.message.TensorFloat\"\xac\x01\n\x08Timestep\x12&\n\x08\x64iscount\x18\x01 \x01(\x0b\x32\x14.message.TensorFloat\x12)\n\x0bobservation\x18\x02 \x01(\x0b\x32\x14.message.TensorFloat\x12$\n\x06reward\x18\x03 \x01(\x0b\x32\x14.message.TensorFloat\x12\'\n\tstep_type\x18\x04 \x01(\x0b\x32\x14.message.TensorInt32\"*\n\x0bTensorFloat\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"*\n\x0bTensorInt32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"!\n\nNamedTuple\x12\x13\n\x0bTensorFloat\x18\x01 \x03(\x02\"\x82\x01\n\nTrajectory\x12$\n\tagent_out\x18\x01 \x01(\x0b\x32\x11.message.AgentOut\x12)\n\x0b\x61gent_state\x18\x02 \x01(\x0b\x32\x14.message.TensorFloat\x12#\n\x08timestep\x18\x03 \x01(\x0b\x32\x11.message.Timestep\"]\n\x0bLayerWeight\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x01\x62\x18\x02 \x01(\x0b\x32\x14.message.TensorFloat\x12\x1f\n\x01w\x18\x03 \x01(\x0b\x32\x14.message.TensorFloat\"H\n\x0bModelParams\x12\x13\n\x0b\x66rame_count\x18\x01 \x01(\x05\x12$\n\x06params\x18\x02 \x03(\x0b\x32\x14.message.LayerWeight2\xcc\x01\n\x0bInformation\x12I\n\x10InsertTrajectory\x12\x13.message.Trajectory\x1a\x1e.message.InsertTrajectoryReply\"\x00\x12>\n\tGetParams\x12\x19.message.GetParamsRequest\x1a\x14.message.ModelParams\"\x00\x12\x32\n\x04Quit\x12\x14.message.QuitRequest\x1a\x12.message.QuitReply\"\x00\x62\x06proto3')
)




_INSERTTRAJECTORYREPLY = _descriptor.Descriptor(
  name='InsertTrajectoryReply',
  full_name='message.InsertTrajectoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='message.InsertTrajectoryReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_GETPARAMSREQUEST = _descriptor.Descriptor(
  name='GetParamsRequest',
  full_name='message.GetParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=86,
)


_QUITREQUEST = _descriptor.Descriptor(
  name='QuitRequest',
  full_name='message.QuitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=101,
)


_QUITREPLY = _descriptor.Descriptor(
  name='QuitReply',
  full_name='message.QuitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=114,
)


_GETPARAMSREPLY = _descriptor.Descriptor(
  name='GetParamsReply',
  full_name='message.GetParamsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_count', full_name='message.GetParamsReply.frame_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='message.GetParamsReply.params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=169,
)


_AGENTOUT = _descriptor.Descriptor(
  name='AgentOut',
  full_name='message.AgentOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='message.AgentOut.action', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy_logits', full_name='message.AgentOut.policy_logits', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='message.AgentOut.values', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=303,
)


_TIMESTEP = _descriptor.Descriptor(
  name='Timestep',
  full_name='message.Timestep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='discount', full_name='message.Timestep.discount', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation', full_name='message.Timestep.observation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='message.Timestep.reward', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_type', full_name='message.Timestep.step_type', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=478,
)


_TENSORFLOAT = _descriptor.Descriptor(
  name='TensorFloat',
  full_name='message.TensorFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='message.TensorFloat.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='message.TensorFloat.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=522,
)


_TENSORINT32 = _descriptor.Descriptor(
  name='TensorInt32',
  full_name='message.TensorInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='message.TensorInt32.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='message.TensorInt32.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=566,
)


_NAMEDTUPLE = _descriptor.Descriptor(
  name='NamedTuple',
  full_name='message.NamedTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TensorFloat', full_name='message.NamedTuple.TensorFloat', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=568,
  serialized_end=601,
)


_TRAJECTORY = _descriptor.Descriptor(
  name='Trajectory',
  full_name='message.Trajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_out', full_name='message.Trajectory.agent_out', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_state', full_name='message.Trajectory.agent_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestep', full_name='message.Trajectory.timestep', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=734,
)


_LAYERWEIGHT = _descriptor.Descriptor(
  name='LayerWeight',
  full_name='message.LayerWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='message.LayerWeight.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='message.LayerWeight.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='message.LayerWeight.w', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=736,
  serialized_end=829,
)


_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='message.ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_count', full_name='message.ModelParams.frame_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='message.ModelParams.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=831,
  serialized_end=903,
)

_AGENTOUT.fields_by_name['action'].message_type = _TENSORINT32
_AGENTOUT.fields_by_name['policy_logits'].message_type = _TENSORFLOAT
_AGENTOUT.fields_by_name['values'].message_type = _TENSORFLOAT
_TIMESTEP.fields_by_name['discount'].message_type = _TENSORFLOAT
_TIMESTEP.fields_by_name['observation'].message_type = _TENSORFLOAT
_TIMESTEP.fields_by_name['reward'].message_type = _TENSORFLOAT
_TIMESTEP.fields_by_name['step_type'].message_type = _TENSORINT32
_TRAJECTORY.fields_by_name['agent_out'].message_type = _AGENTOUT
_TRAJECTORY.fields_by_name['agent_state'].message_type = _TENSORFLOAT
_TRAJECTORY.fields_by_name['timestep'].message_type = _TIMESTEP
_LAYERWEIGHT.fields_by_name['b'].message_type = _TENSORFLOAT
_LAYERWEIGHT.fields_by_name['w'].message_type = _TENSORFLOAT
_MODELPARAMS.fields_by_name['params'].message_type = _LAYERWEIGHT
DESCRIPTOR.message_types_by_name['InsertTrajectoryReply'] = _INSERTTRAJECTORYREPLY
DESCRIPTOR.message_types_by_name['GetParamsRequest'] = _GETPARAMSREQUEST
DESCRIPTOR.message_types_by_name['QuitRequest'] = _QUITREQUEST
DESCRIPTOR.message_types_by_name['QuitReply'] = _QUITREPLY
DESCRIPTOR.message_types_by_name['GetParamsReply'] = _GETPARAMSREPLY
DESCRIPTOR.message_types_by_name['AgentOut'] = _AGENTOUT
DESCRIPTOR.message_types_by_name['Timestep'] = _TIMESTEP
DESCRIPTOR.message_types_by_name['TensorFloat'] = _TENSORFLOAT
DESCRIPTOR.message_types_by_name['TensorInt32'] = _TENSORINT32
DESCRIPTOR.message_types_by_name['NamedTuple'] = _NAMEDTUPLE
DESCRIPTOR.message_types_by_name['Trajectory'] = _TRAJECTORY
DESCRIPTOR.message_types_by_name['LayerWeight'] = _LAYERWEIGHT
DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertTrajectoryReply = _reflection.GeneratedProtocolMessageType('InsertTrajectoryReply', (_message.Message,), {
  'DESCRIPTOR' : _INSERTTRAJECTORYREPLY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.InsertTrajectoryReply)
  })
_sym_db.RegisterMessage(InsertTrajectoryReply)

GetParamsRequest = _reflection.GeneratedProtocolMessageType('GetParamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPARAMSREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.GetParamsRequest)
  })
_sym_db.RegisterMessage(GetParamsRequest)

QuitRequest = _reflection.GeneratedProtocolMessageType('QuitRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUITREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.QuitRequest)
  })
_sym_db.RegisterMessage(QuitRequest)

QuitReply = _reflection.GeneratedProtocolMessageType('QuitReply', (_message.Message,), {
  'DESCRIPTOR' : _QUITREPLY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.QuitReply)
  })
_sym_db.RegisterMessage(QuitReply)

GetParamsReply = _reflection.GeneratedProtocolMessageType('GetParamsReply', (_message.Message,), {
  'DESCRIPTOR' : _GETPARAMSREPLY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.GetParamsReply)
  })
_sym_db.RegisterMessage(GetParamsReply)

AgentOut = _reflection.GeneratedProtocolMessageType('AgentOut', (_message.Message,), {
  'DESCRIPTOR' : _AGENTOUT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.AgentOut)
  })
_sym_db.RegisterMessage(AgentOut)

Timestep = _reflection.GeneratedProtocolMessageType('Timestep', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTEP,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Timestep)
  })
_sym_db.RegisterMessage(Timestep)

TensorFloat = _reflection.GeneratedProtocolMessageType('TensorFloat', (_message.Message,), {
  'DESCRIPTOR' : _TENSORFLOAT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.TensorFloat)
  })
_sym_db.RegisterMessage(TensorFloat)

TensorInt32 = _reflection.GeneratedProtocolMessageType('TensorInt32', (_message.Message,), {
  'DESCRIPTOR' : _TENSORINT32,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.TensorInt32)
  })
_sym_db.RegisterMessage(TensorInt32)

NamedTuple = _reflection.GeneratedProtocolMessageType('NamedTuple', (_message.Message,), {
  'DESCRIPTOR' : _NAMEDTUPLE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.NamedTuple)
  })
_sym_db.RegisterMessage(NamedTuple)

Trajectory = _reflection.GeneratedProtocolMessageType('Trajectory', (_message.Message,), {
  'DESCRIPTOR' : _TRAJECTORY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.Trajectory)
  })
_sym_db.RegisterMessage(Trajectory)

LayerWeight = _reflection.GeneratedProtocolMessageType('LayerWeight', (_message.Message,), {
  'DESCRIPTOR' : _LAYERWEIGHT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.LayerWeight)
  })
_sym_db.RegisterMessage(LayerWeight)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAMS,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.ModelParams)
  })
_sym_db.RegisterMessage(ModelParams)



_INFORMATION = _descriptor.ServiceDescriptor(
  name='Information',
  full_name='message.Information',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=906,
  serialized_end=1110,
  methods=[
  _descriptor.MethodDescriptor(
    name='InsertTrajectory',
    full_name='message.Information.InsertTrajectory',
    index=0,
    containing_service=None,
    input_type=_TRAJECTORY,
    output_type=_INSERTTRAJECTORYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetParams',
    full_name='message.Information.GetParams',
    index=1,
    containing_service=None,
    input_type=_GETPARAMSREQUEST,
    output_type=_MODELPARAMS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Quit',
    full_name='message.Information.Quit',
    index=2,
    containing_service=None,
    input_type=_QUITREQUEST,
    output_type=_QUITREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFORMATION)

DESCRIPTOR.services_by_name['Information'] = _INFORMATION

# @@protoc_insertion_point(module_scope)
